---
- name: Configure Apache2 Web Server
  hosts: webservers
  become: yes
  roles:
    - update_apt
    - apache2
  tags:
    - web

- name: Configure MySQL Server
  hosts: db
  become: yes
  roles:
    - update_apt
    - mysql
  vars:
    mysql_root_password: "secure_password"
    mysql_user: "fbynum67"
    mysql_password: "secure_password"
    mysql_database: "devops"
    mysql_import_data: yes
  tags:
    - database

