---
- name: Update web servers
  hosts: webservers
  become: yes

  tasks:
  - name: Ensure apache is at the latest version
    ansible.builtin.package:
      name:
        - apache2
        - python-apt
      state: latest

  - name: Create a symbolic link
    ansible.builtin.file:
      src: /etc/apache2/mods-available/headers.load
      dest: /etc/apache2/mods-enabled/headers.load
      state: link
      force: yes

  - name: Restart service httpd, in all cases
    ansible.builtin.service:
      name: apache2
      state: restarted
